version: '3'
services:
    fauxtto:
        image: php:apache
        ports:
            - "8080:80"
        volumes:
            - ./www/:/var/www/html/
        restart: always
        stop_grace_period: 0s
